### ISSUE TITLE
add x-client-name as a header for Zalando Shop API requests

### ISSUE THREAD

**Issue by goekhanak** [zalando/zalmemo#2]
Add  header  'x-client-name’ 'zalmemo' for Zalando Shop API so that they can track those requests.

**Comment by hjacobs** [comment]
Why don't you use the `User-Agent` header (which can be set as needed)?

**Comment by goekhanak** [comment]
@hjacobs  'User-Agent' set automatically from browser why should i try to overwrite it ?
